name: Test GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Récupérer le code du repository
        uses: actions/checkout@v4

      - name: 🔍 Afficher le contenu du projet
        run: ls -la
